// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0AdNS2Lz9chCiIE147z3YM5cNp5mbIo',
    appId: '1:439157694327:web:73081abe3378b96690cb72',
    messagingSenderId: '439157694327',
    projectId: 'ott-app-a9250',
    authDomain: 'ott-app-a9250.firebaseapp.com',
    storageBucket: 'ott-app-a9250.appspot.com',
    measurementId: 'G-V3YYY9DTD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycFFt28NC5vdLAuobK9hrPcx7gAjxg_g',
    appId: '1:439157694327:android:7a076968b2768d0790cb72',
    messagingSenderId: '439157694327',
    projectId: 'ott-app-a9250',
    storageBucket: 'ott-app-a9250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TKbRKKXdnJbHKYLJuC5KV6sWvVf2b7w',
    appId: '1:439157694327:ios:493c2826b3e83e5690cb72',
    messagingSenderId: '439157694327',
    projectId: 'ott-app-a9250',
    storageBucket: 'ott-app-a9250.appspot.com',
    iosClientId: '439157694327-phl513ttfhoi82dbgkebqosvrfvsir9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TKbRKKXdnJbHKYLJuC5KV6sWvVf2b7w',
    appId: '1:439157694327:ios:493c2826b3e83e5690cb72',
    messagingSenderId: '439157694327',
    projectId: 'ott-app-a9250',
    storageBucket: 'ott-app-a9250.appspot.com',
    iosClientId: '439157694327-phl513ttfhoi82dbgkebqosvrfvsir9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottDemoApp',
  );
}
